Ukeyboard creator
GUI vkb compiler, runs on the tablet.

diff --git a/cpanel/ukeyboard-set b/cpanel/ukeyboard-set
--- a/cpanel/ukeyboard-set
+++ b/cpanel/ukeyboard-set
@@ -1,20 +1,41 @@
 #!/bin/sh
+store=
+if [ "$1" = "-s" ]; then
+	store=1
+	shift
+fi
+
 if [ -z "$1" -o -z "$2" ]; then
 	echo "ukeyboard-set: Missing parameters."
 	exit 1
 fi
-
 dest="/usr/share/keyboards/$2.vkb"
+
+if [ "$1" = "-r" -a ! -f "$dest-saved" ]; then
+	echo "ukeyboard-set: No previous file stored."
+	exit 4
+fi
+
 if [ -f "$dest" ]; then
 	if [ ! -h "$dest" ]; then
 		echo "ukeyboard-set: Destination $dest exists and is not a symlink."
 		exit 2
 	fi
-	rm "$dest"
-	if [ -f "$dest" ]; then
-		echo "ukeyboard-set: Cannot delete current symlink $dest."
-		exit 3
+	if [ "$store" != 1 -o -f "$dest-saved" ]; then
+		rm "$dest"
+		if [ -f "$dest" ]; then
+			echo "ukeyboard-set: Cannot delete current symlink $dest."
+			exit 3
+		fi
+	else
+		mv "$dest" "$dest-saved"
 	fi
 fi
 
-ln -s "../ukeyboard/$1.vkb" "$dest"
+if [ "$1" = "-r" ]; then
+	mv "$dest-saved" "$dest"
+elif [ "$store" = 1 ]; then
+	ln -s "$1" "$dest"
+else
+	ln -s "../ukeyboard/$1.vkb" "$dest"
+fi
